# Generated by Django 5.0.1 on 2024-02-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
