# Generated by Django 5.0.1 on 2024-02-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
