# Generated by Django 5.0.1 on 2024-02-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
