# Generated by Django 5.0.1 on 2024-02-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
