# Generated by Django 5.0.1 on 2024-02-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_phone_alter_order_pincode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
