# Generated by Django 5.0.1 on 2024-02-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_cart_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
