# Generated by Django 5.0.1 on 2024-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_cart_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
