# Generated by Django 5.0.1 on 2024-03-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
