# Generated by Django 5.0.1 on 2024-03-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
