# Generated by Django 5.0.1 on 2024-03-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='a@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='fname',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='lname',
            field=models.CharField(default='n', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=3216549870, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(default=456789, max_length=150),
            preserve_default=False,
        ),
    ]
