# Generated by Django 5.0.1 on 2024-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatched'), (3, 'Out for delivery'), (4, 'Delivered'), (5, 'Cancel'), (6, 'Return')], default=1),
        ),
    ]
