# Generated by Django 5.0.1 on 2024-03-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
