# Generated by Django 5.0.1 on 2024-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
