# Generated by Django 5.0.1 on 2024-03-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_remove_cart_coupon_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
