# Generated by Django 5.0.1 on 2024-03-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rename_coupon_cart_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupons',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
