# Generated by Django 5.0.1 on 2024-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_coupon_cart_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(default='Percentage', max_length=100),
        ),
    ]
