# Generated by Django 5.0.1 on 2024-03-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
