# Generated by Django 5.0.1 on 2024-03-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
