# Generated by Django 5.0.1 on 2024-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_cart_saved_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
