# Generated by Django 5.0.1 on 2024-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_wishlist_products_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='products',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
