# Generated by Django 5.0.1 on 2024-03-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
