# Generated by Django 5.0.1 on 2024-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
