# Generated by Django 5.0.1 on 2024-03-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_remove_wishlist_quantity_wishlistitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
