# Generated by Django 5.0.1 on 2024-04-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_remove_wishlistitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('O', 'Ordinary')], max_length=2, null=True),
        ),
    ]
