# Generated by Django 5.0.1 on 2024-04-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sub_category'),
        ),
    ]
