# Generated by Django 5.0.1 on 2024-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_brand_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/brand-img'),
        ),
    ]
