# Generated by Django 5.0.1 on 2024-04-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='valid_to',
        ),
    ]
