# Generated by Django 5.0.1 on 2024-04-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_remove_productoffer_valid_from_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
