# Generated by Django 5.0.1 on 2024-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='sub_category_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
