# Generated by Django 5.0.1 on 2024-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_remove_product_discount_product_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_offer',
            field=models.IntegerField(default=0),
        ),
    ]
