# Generated by Django 5.0.1 on 2024-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_product_price_after_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amt',
            field=models.IntegerField(default=0),
        ),
    ]
