# Generated by Django 5.0.1 on 2024-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_product_discount_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_offer_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
