# Generated by Django 5.0.1 on 2024-04-09 01:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_product_category_offer_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_offer_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_amt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_after_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_offer_amount',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='sub_category_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.offer'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.offer'),
        ),
    ]
