# Generated by Django 5.0.1 on 2024-04-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_offer_remove_product_category_offer_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='related_offers', to='store.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_subcategories',
            field=models.ManyToManyField(blank=True, to='store.sub_category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_to_all_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_to_all_subcategories',
            field=models.BooleanField(default=False),
        ),
    ]
