# Generated by Django 5.0.1 on 2024-04-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_remove_sub_category_offer_offer_applicable_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='applicable_subcategories',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='applicable_to_all_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='applicable_to_all_subcategories',
        ),
    ]
