# Generated by Django 5.0.1 on 2024-04-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_remove_offer_applicable_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.offer'),
        ),
    ]
