# Generated by Django 5.0.1 on 2024-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_cartitem_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_price',
            new_name='coupon_discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_discount_price',
            field=models.FloatField(default=0),
        ),
    ]
