# Generated by Django 5.0.1 on 2024-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_rename_discount_price_order_coupon_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_after_offer',
            field=models.FloatField(default=0),
        ),
    ]
