# Generated by Django 5.0.1 on 2024-04-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_order_total_after_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_after_offer',
        ),
    ]
