# Generated by Django 5.0.1 on 2024-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_remove_order_total_after_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_offer',
            field=models.IntegerField(default=0),
        ),
    ]
