# Generated by Django 5.0.1 on 2024-04-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_product_final_price_product_total_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
        ),
    ]
