# Generated by Django 5.0.1 on 2024-04-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_rename_payment_id_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
