# Generated by Django 5.0.1 on 2024-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default='Your perfect destination for day to day needs.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(default='A journey worth of 35 years', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Quality Traders', max_length=50),
            preserve_default=False,
        ),
    ]
