# Generated by Django 5.0.1 on 2024-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_banner_description_banner_is_listed_banner_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
