# Generated by Django 5.0.1 on 2024-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_alter_banner_description_alter_banner_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
