# Generated by Django 5.0.1 on 2024-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_banner_button_text_alter_banner_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
