# Generated by Django 5.0.1 on 2024-04-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_alter_wallet_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
