# Generated by Django 5.0.1 on 2024-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='rejection_message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
