# Generated by Django 5.0.1 on 2024-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_returnrequest_rejection_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatched'), (3, 'Out for delivery'), (4, 'Delivered'), (5, 'Cancel'), (6, 'Return'), (7, 'Not Returnable')], default=1),
        ),
    ]
