# Generated by Django 5.0.1 on 2024-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='rejection_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
