# Generated by Django 5.0.1 on 2024-04-29 12:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0105_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fname',
            field=models.CharField(default='Test', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(default='User', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='597458', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Test Address', max_length=250),
            preserve_default=False,
        ),
    ]
