# Generated by Django 5.0.1 on 2024-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0106_order_email_order_fname_order_lname_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
    ]
