# Generated by Django 5.0.1 on 2024-05-07 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0107_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('Money', 'Money'), ('Percentage', 'Percentage')], default='Percentage', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 5, 41, 17, 986801, tzinfo=datetime.timezone.utc)),
        ),
    ]
