# Generated by Django 5.0.1 on 2024-05-13 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_alter_coupon_type_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
