# Generated by Django 5.0.1 on 2024-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0113_alter_coupon_type_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="ecommerce\\p-img\\default-product-image.jpg",
                upload_to="ecommerce/p-img",
            ),
        ),
    ]
