# Generated by Django 5.0.1 on 2024-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0114_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="ecommerce/p-img/default-product-image.jpg",
                upload_to="ecommerce/p-img",
            ),
        ),
    ]
