# Generated by Django 5.0.1 on 2024-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0115_alter_category_name_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Percentage", "Percentage"), ("Money", "Money")],
                default="Percentage",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Order Placed"),
                    (3, "Dispatched"),
                    (4, "Out for delivery"),
                    (5, "Delivered"),
                    (6, "Cancel"),
                    (7, "Return"),
                    (8, "Not Returnable"),
                ],
                default=1,
            ),
        ),
    ]
