# Generated by Django 5.0.1 on 2024-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0116_alter_coupon_type_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Money", "Money"), ("Percentage", "Percentage")],
                default="Percentage",
                max_length=100,
            ),
        ),
    ]
