# Generated by Django 5.0.1 on 2024-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0117_alter_coupon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Percentage", "Percentage"), ("Money", "Money")],
                default="Percentage",
                max_length=100,
            ),
        ),
    ]
