# Generated by Django 5.0.1 on 2024-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0118_alter_coupon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sub_category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Money", "Money"), ("Percentage", "Percentage")],
                default="Percentage",
                max_length=100,
            ),
        ),
    ]
