# Generated by Django 5.0.1 on 2024-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0119_brand_is_active_category_is_active_product_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Percentage", "Percentage"), ("Money", "Money")],
                default="Percentage",
                max_length=100,
            ),
        ),
    ]
