# Generated by Django 5.0.1 on 2025-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0120_alter_coupon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Money", "Money"), ("Percentage", "Percentage")],
                default="Percentage",
                max_length=100,
            ),
        ),
    ]
