"""
Django settings for quality-traders project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# .env
from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)
# DEBUG = True
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)

ALLOWED_HOSTS_STRING = config('ALLOWED_HOSTS', default='')
if ALLOWED_HOSTS_STRING:
    ALLOWED_HOSTS = ALLOWED_HOSTS_STRING.split(',')

CSRF_TRUSTED_ORIGINS_STRING = config('CSRF_TRUSTED_ORIGINS', default='')
if CSRF_TRUSTED_ORIGINS_STRING:
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS_STRING.split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "accounts.apps.AccountsConfig",
    "store.apps.StoreConfig",
    "dashboard.apps.DashboardConfig",
    "django_filters",
    "phonenumber_field",
    "crispy_forms",
    "crispy_bootstrap3",
    "bootstrap_datepicker_plus",
    "chartjs",
    "whitenoise.runserver_nostatic",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dashboard.middleware.LogoutInactiveUser",
]


ROOT_URLCONF = "quality-traders.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "store.context_processors.cart_count",
                "store.context_processors.wishlist_count",
                # 'store.context_processors.filter_context',
            ],
        },
    },
]

WSGI_APPLICATION = "quality-traders.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default="5432"),
    },
    # "gis_db": {
    #     "ENGINE": "django.contrib.gis.db.backends.postgis",
    #     "NAME": config("GIS_DB_NAME"),
    #     "USER": config("GIS_DB_USER"),
    #     "PASSWORD": config("GIS_DB_PASSWORD"),
    #     "HOST": config("GIS_DB_HOST"),
    #     "PORT": config("GIS_DB_PORT", default="5432"),
    # },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE")

TIME_ZONE = config("TIME_ZONE")

USE_I18N = config("USE_I18N")

USE_TZ = config("USE_TZ")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATICFIELDS_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# smtp configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap3"
CRISPY_TEMPLATE_PACK = "bootstrap3"

# Path for GDAL and GEOS (part of PostGIS)
GDAL_LIBRARY_PATH = "C:\\OSGeo4W\\bin\\gdal308.dll"
GEOS_LIBRARY_PATH = "C:\\OSGeo4W\\bin\\geos_c.dll"

# Razorpay credentials
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
RAZOR_KEY_ID = config("RAZOR_KEY_ID")
RAZOR_KEY_SECRET = config("RAZOR_KEY_SECRET")

#AWS S3
# AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
# AWS_S3_SIGNATURE_NAME = config("AWS_S3_SIGNATURE_NAME")
# AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME")
# AWS_S3_FILE_OVERWRITE = config("AWS_S3_FILE_OVERWRITE", default=False, cast=bool)
# AWS_DEFAULT_ACL = config("AWS_DEFAULT_ACL")
# AWS_S3_VERIFY = config("AWS_S3_VERIFY", default=True, cast=bool)
# DEFAULT_FILE_STORAGE = config("DEFAULT_FILE_STORAGE")

AWS_ACCESS_KEY_ID = "AKIA2UC3DJ5M6SGLGMIG"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "myqualitybucket"
AWS_S3_SIGNATURE_NAME = "s3v4"
AWS_S3_REGION_NAME = "eu-north-1"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# print(AWS_ACCESS_KEY_ID)
# print(AWS_SECRET_ACCESS_KEY)
# print(AWS_STORAGE_BUCKET_NAME)
# print(AWS_S3_SIGNATURE_NAME)
# print(AWS_S3_REGION_NAME)
# print(AWS_S3_FILE_OVERWRITE)
# print(AWS_DEFAULT_ACL)
# print(AWS_S3_VERIFY)
# print(DEFAULT_FILE_STORAGE)