# Generated by Django 5.0.1 on 2024-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='ashiqalit@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='ashiqalit@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='ali', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='ashiqali', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000021E1FCBC9A0>', max_length=200),
        ),
    ]
