# Generated by Django 5.0.1 on 2024-03-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ecommerce/profile_pic/default.png', upload_to='ecommerce/profile_pic'),
        ),
    ]
