# Generated by Django 5.0.1 on 2024-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_uid_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000024C5BA6C9A0>', max_length=200),
        ),
    ]
